spring:
  application:
    name: backend-boxboxd
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boxboxd?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATABASE_PASSWORD}
    password: ${DATABASE_USER}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true


